- locale.go
store the .po (and .mo) files under a subdir called LC_MESSAGES is very common (I think it's the official directory layout supported by gettext).
This patch adds the support for the LC_MESSAGES subdir and, as a consequence, it is possible to share the same directory with other tools (for example a Django site)
> added support for .po files stored in a LC_MESSAGES subdir

- gotext_test.go
- locale_test.go
- po.go
- po_test.go
- Removed `msgid` and `msgstr` from the tests where they are placed before the header. As I understand it, that is not according to spec. https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html
- Added support for multi-line `msgid` entries
> Add support for multi-line msgid

- fixtures/ar/categories.po
- fixtures/ar/no_plural_header.po
- gotext.go
- gotext_test.go
- locale.go
- locale_test.go
instead of calling Translation.GetN with a default of plural=1
* add correct Arabic plural rules to test
- New Pull Requests should include a good description of what's being merged. 
- Ideally, all Pull Requests are preceded by a discussion initiated in an Issue on this repository. 
- For bug fixes is mandatory to have tests that cover and fail when the bug is present and will pass after this Pull Request.
- For changes and improvements, new tests have to be provided to cover the new features.
Fix (https://github.com/leonelquinteros/gotext/issues/39)
...
Adding the correct Pluralform rules in the existing Arabic test case caused it to fail in a way that's consistent with https://github.com/leonelquinteros/gotext/issues/39
The code changes provided allowed the test to pass
...
> call Translation.Get & GetC directly 

- domain.go
- domain_test.go
- go.mod
- go.sum
- gotext_test.go
- helper_test.go
- locale.go
- locale_test.go
- mo.go
- mo_test.go
- po.go
- po_test.go
- translator.go
This is an attempt at tackling #43. I think I was able to keep the public methods unchanged, though there may be some subtle nuances not accounted for. But largely this should be a transparent change; the only change needed in the tests was related to the private pluralForms tests, and those have been refactored to be table-driven. I also replaced the most commonly-used string in the tests with a constant.
Improvement, reducing duplicate code
#43
> move common po.go/mo.go code to domain.go

- domain.go
- domain_test.go
- locale.go
- locale_test.go
Per discussion in #46, this is a simple way to allow access to all the translations in a locale. It is just iterating over all domains, and the domain method creates a copy of each translation and returns the resulting map.
This is a new feature that will make it possible to enumerate all the translations that have been loaded.
It does not support contexts as this time.
> Add GetTranslations methods to Locale and Domain

- po.go
Documentation fix.
The Godoc string for `(*Po).Parse` currently does not match the function's signature.
> Fix arg type in docstring for (*Po).Parse

- domain.go
- domain_test.go
Fixes https://github.com/leonelquinteros/gotext/issues/60.
As described in the issue, this:
```
po := gotext.NewPo()
strings := map[string]string{"myid": "test string\nwith \"newline\""}
for k, v := range strings {
po.Set(k, v)
}
po_bytes, _ := po.MarshalText()
fmt.Println(string(po_bytes))
```
currently outputs this:
```
msgid ""
msgstr ""
msgid "myid"
msgstr "test string
with "newline""
```
This breaks format and causes xgettext to throw errors if the file is used. After this PR, the output is:
```
[...]
msgid "myid"
msgstr "test string"
"with \"newline\""
``` 
My apologies for not adding tests. Please feel free to edit/push to this branch.
> Format quotation marks and newlines for PO export

- LICENSE
- plurals/compiler.go
- plurals/compiler_test.go
- plurals/expression.go
- plurals/genfixture.py
- plurals/math.go
- plurals/tests.go
Mhh... :thinking: Something else.
It is a suggestion how to adjust the copyright header for the plurals package so that no rights of the original authors and no licenses are violated.
I am not a lawyer and have no legal education. This is just a suggestion so that Issue #50 can be closed and everyone is happy.
> Changing the copyright header for plurals package

- domain.go
- domain_test.go
- gotext.go
- gotext_test.go
- introspector.go
- locale.go
- mo.go
- po.go
- translation.go
- translator.go
Hello. Thanks for creating gettext-compatible Go package, it is much more elegant than the existing alternatives!
After reading #42, I decided to take a look into the package. The original rejected PR #41 already had the core ideas, which I adopted into a new design.
Since the originally suggested change would break the API compatibility, I decided to take another round and implemented `IsTranslated*` methods that can be used to detect whether a string has translation or not. They bubble up from individual `Translation`s up into the public module methods.
The patch is split into three files. The two big changes contain their own tests. This patch should not be able to change any behavior, it does not alter the internal logic at all.
This PR is an improvement.
This PR implements methods to …
> Runtime translation detection

- locale.go
- locale_test.go
for proposal https://github.com/leonelquinteros/gotext/issues/75
this is to expose lang from Locale with `Locale.GetLanguage`
> feat: Add language getter for Locale

- cli/xgotext/fixtures/i18n/default.po
- cli/xgotext/fixtures/i18n/domain2.po
- cli/xgotext/fixtures/i18n/translations.po
- cli/xgotext/fixtures/main.go
- cli/xgotext/parser/dir/golang.go
- cli/xgotext/parser/domain.go
- cli/xgotext/parser/pkg-tree/golang.go
- cli/xgotext/parser/pkg-tree/golang_test.go
- domain.go
- domain_test.go
This is fix on multiline and backquote supports for i18n pot and po file export.
This changes impacts both the xgettext tooling and po file marshalling to text to conform to gettext specification: https://www.gnu.org/software/gettext/manual/html_node/Normalizing.html
When exporting from a po and extracting text from files, there are multiple issues for multi-line and backquotes usage. This is fine until we use standard gettext tooling for compiling them to mo files.
multilines are printed as is, instead of follow the gettext spec ( )
strings with backquotes as printed as “msgid this is my string”, which then can’t be compiled to mo files.
multilines strings with backquotes are formatted as multi-lines to, without closing quotes on each lines.
The loading is correct though, this only …
> Fix multiline export

- cli/xgotext/parser/domain.go
- New Pull Requests should include a good description of what's being merged. 
- Ideally, all Pull Requests are preceded by a discussion initiated in an Issue on this repository. 
- For bug fixes is mandatory to have tests that cover and fail when the bug is present and will pass after this Pull Request.
- For changes and improvements, new tests have to be provided to cover the new features.
This is a fix.
Before we could get some different order on consecutive runs when running the pkgtree:
```
#: cmd/foo/client/version.go:27
#: cmd/foo/daemon/version.go:23
#: cmd/bar/commands/version.go:24
msgid "some string"
msgstr ""
```
But sometimes, the dependency order could become:
```
#: cmd/foo/daemon/version.go:23
#: cmd/foo/client/version.go:27
#: cmd/bar/commands/version.go:24
msgid "some …
```
> Order locations in ascii order

- gotext.go
- gotext_test.go
- locale.go
This patch adds support for fallback translations. `pt_BR:pt:es` makes it possible to use Brazilian Portuguese, fallback to default Portuguese and to Spanish when the translation is not available.
- This patch changes the `config` struct, and internal implementation of functions that work with it.
- It changes `Get*()` functions to iterate over loaded languages, instead of using the only one.
- It changes `IsTranslated*()` functions to include new required argument of the language to be checked.
- Adds `Locale.GetActualLanguage()`, required by the `IsTranslated*()` functions. This one may need a bit of polishing.
- Is there a better name?
- Is there a better place?
- Should it be able to handle empty argument as a wildcard, making it possible to return `true` if *some* translation exists?
> Add support for multiple languages

- gotext.go
- gotext_test.go
- locale.go
Reverts leonelquinteros/gotext#73
> Revert "Add support for multiple languages"

- domain.go
- go.mod
- go.sum
It's an improvement.
I'm currently looking for Go gettext implementations for a private project and came across this really great looking library. Thank you very much for your work! <3 One of my criteria to select a library is how many dependencies it brings in. The fewer, the better.
While figuring out what both dependencies in gotext are used for, I quickly noticed that one is actually useless at the moment. The `tag` field is only set but never used, so it can be dropped. It was [introduced three years ago](https://github.com/leonelquinteros/gotext/commit/bb276626f3c27135c5d84addfae510979bb1c5bc) and was even not used back then. I didn't check the history any further, though. Removing the private field allows getting rid of a third-party dependency entirely.
> Remove unused dependency

- po.go
It's a documentation fix.
There is no `NewPoTranslator` function, it's called `NewPo` instead.
> Fix typo in documentation

- domain.go
- domain_test.go
- gotext.go
- gotext_test.go
- helper.go
- mo.go
- po.go
- translator.go
I believe this was discussed and accepted in #92 but that PR apparently had some issues and was never merged. I independently encountered and fixed the same bug, so here's another PR that should merge cleanly. Appreciate the great library.
> Fix IsTranslated* functions using n directly rather than using the nth plural form

- go.mod
- locale.go
- locale_test.go
Go embed FS are 
- New Pull Requests should include a good description of what's being merged. 
- Ideally, all Pull Requests are preceded by a discussion initiated in an Issue on this repository. 
- For bug fixes is mandatory to have tests that cover and fail when the bug is present and will pass after this Pull Request.
- For changes and improvements, new tests have to be provided to cover the new features.
yes, 
- allows to use go embed by adding a backwards compatible `NewLocaleFSWithPath` function, 
- adds tests for a embed.FS, addressing #68  
- bumps go version to 1.16 which is the minimum required to use embed package
Bumping go version can be troublesome for existing users, although embed.FS tests will not be supported. It is possible to keep 1.13 compatibility by removing the …
> go embed fs with path

- domain.go
- domain_test.go
this add `GetCtxTranslations()` to domain to expose the translations in context just like `GetTranslations()` does without context
improvement
...
it adds the possibility to retrieve to context translation keys
...
> add GetCtxTranslations() to domain

- cli/xgotext/parser/dir/golang.go
- cli/xgotext/parser/domain.go
Fix
---
Fixes quote and backslash escaping in PO file generation. The previous implementation couldn't properly handle strings with quotes or special characters, causing syntax errors in the generated files. Replaced string splitting with character-by-character processing to correctly escape all special characters and handle multiline strings properly.
---
It didn't even have its own tests before, in the first place -_-
> Fixed quote escaping issues in PO file formatting

- .gitignore
- cli/xgotext/parser/dir/golang.go
- cli/xgotext/parser/gofile.go
- cli/xgotext/parser/pkg-tree/golang.go
- New Pull Requests should include a good description of what's being merged. 
- Ideally, all Pull Requests are preceded by a discussion initiated in an Issue on this repository. 
- For bug fixes is mandatory to have tests that cover and fail when the bug is present and will pass after this Pull Request.
- For changes and improvements, new tests have to be provided to cover the new features.
...
...
> Refactor parser object

- locale.go
> fix IsTranslated predicates
